version: '3.4'

services:
  prom:
    image: prom/prometheus
    container_name: prommetheus
    networks:
      - promnet
    volumes:
      - ${PROM_CONFIG_PATH- ./prometheus.yml}:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    networks:
      - promnet
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE- }
    restart: always
    depends_on:
      - prom
    ports:
      - "9104:9104"
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - promnet
    restart: always
    ports:
      - "9100:9100"

networks:
  promnet:
    driver: bridge


