version: '3.4'

services:
  prom:
    image: prom/prometheus
    container_name: prommetheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE- }
    ports:
      - "9104:9104"
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"


