global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['yourhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['yourhost:9104']

  - job_name: 'node'
    static_configs:
      - targets: ['yourhost:9100']
